### ISSUE TITLE
Support informal `NO_COLOR` standard

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1052]
details are here: https://no-color.org/

basically, I think we should honor the `NO_COLOR=1` env var convention and nix any ANSI color on the terminal when this value is set and nonempty. Once we've done so, we should submit a PR [here](https://github.com/jcs/no_color) to add ourselves to the list of projects that support

**Comment by azzamsa** [comment]
I am ready to tackle this.

Please ping me if the team wants to add `--color auto/always/never/` and respect `NO_COLOR` env var.

**Comment by flub** [comment]
> I am ready to tackle this.
> 
> Please ping me if the team wants to add `--color auto/always/never/` and respect `NO_COLOR` env var.

@azzamsa sure, we'd accept a PR for this

**Comment by azzamsa** [comment]
It turns out that Iroh-CLI uses the `Colored` under the hood, which supports `NO_COLOR` out of the box. You can check out its features here: https://github.com/colored-rs/colored?tab=readme-ov-file#features.

The current version of Iroh-CLI already respects the `NO_COLOR` environment variable, thanks to `Colored`.

- When `NO_COLOR` is not set:
![image](https://github.com/n0-computer/iroh/assets/17734314/25c6436b-28d2-47b5-8ffd-9d0519807da7)

- When `NO_COLOR` is set:
![image](https://github.com/n0-computer/iroh/assets/17734314/f9b19912-529a-43ae-a763-7ab0b33ac43c)

If my assumption is correct, then will open a PR here https://github.com/jcs/no_color

**Comment by flub** [comment]
Nice!  I guess this can be closed then.  Feel free to re-open if that's a mistake though.
