### ISSUE TITLE
figure out derp home servers and region ids

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1073]

**Comment by ramfox** [comment]
dumping the knowledge here for now:
- each derp server in a region is expected to be meshed with each other server in that same region
- when a peer advertise itself on the network, it's should specify its region (possibly it's home server)
- in order to contact you, another peer would have to dial any node from that region & would be at most one hop away from you
- when you add a peer to the network map, you also add a specific derp node to talk to them over
- when you dial that peer, you should use the derp server specified in the network map
