### ISSUE TITLE
Fix test_mesh_network

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1247]
This is possibly masking a bug

https://github.com/n0-computer/iroh/blob/1dadcf5465fc4314edd860b026df9cc1fe9d5f67/iroh-net/src/hp/derp/http/mesh_clients.rs#L115

**Comment by ramfox** [comment]
After finally forcing through a run that fails w/ logs. Here is what I've found.

The issue occurs sometimes when forwarding a packet from one node to another.

Sending a packet from Bob to Alice (Bob -> derp server -> derp server -> Alice)
1) `SendPacket` is sent from Bob to the derp server - 49 bytes
2) Bob's derp server receives the `SendPacket` with the correct number of bytes
3) Bob's derp server sees it has a packet forwarder for Alice, so it sends a `ForwardPacket` message to Alice's derp server
81 bytes
4) Alice's derp server receives an `Unknown` packet (read off the wire as the first u8 of the packet) and interprets the number of bytes at 16 (read as the next u32), reads only 16 bytes off the wire & it drops the message (since it is unknown)
5) Since there are more than 16 bytes coming in, Alice's derp server continues to read off the wire
6) this time it receives an `Unknown` packet with what it believes are 823853558, which is over the number of bytes allowed in a packet. It drops the connection to the other derp server.
7) We timeout

We are also getting this panic, that I don't fully understand:
```
thread 'derp::http::mesh_clients::tests::test_mesh_network' panicked at 'tried to drop a ref to Id(322007373356990473), but no such span exists!', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:350:21
```

I'm unclear about exactly which write or read is causing the issue! Looking into it further.

**Comment by dignifiedquire** [comment]
> ```
> thread 'derp::http::mesh_clients::tests::test_mesh_network' panicked at 'tried to drop a ref to Id(322007373356990473), but no such span exists!', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:350:21
> ```

this is related to debug spans, cc @flub
