### ISSUE TITLE
magic_endpoint: allow dialing with just PeerId

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1248]
The magic endpoint stores known addresses of peers in the PeerMap.  This should allows it to keep state across dials and allows successful dials with just a PeerId.  We should allow this.

See https://github.com/n0-computer/iroh/pull/1222#discussion_r1264970532

**Comment by rklaehn** [comment]
I think it is very important that we enable this somehow, soon.

For me this is one of the main selling points of iroh-net. It is very simple to explain: you get all of QUIC, but you can dial by identity (peer id) instead of location (addr).

So why can't we have some (non-persisted) information exchange between the derpers that allow them to figure out a peer -> current derp region mapping?

A peer knows or at least can find out its own region id. So when it connects to its derp region, this information could be distributed between the derpers, no?

At least for me this is extremely valuable to make iroh-net a compelling product that people might be willing to pay for.

**Comment by rklaehn** [comment]
Can't we just hack dial by peer in the most non decentralized way possible? Have a single central database that stores peer -> region, that gets updated every time a peer connects to a derper, and gets queried every time we need to know where a peer is?

Once we go via the relays we are in a somewhat centralized world anyway. So I say let's just hack it for now and then come up with something more pure/decentralized later...

**Comment by rklaehn** [comment]
This: https://github.com/n0-computer/iroh/issues/1636 would solve this.

**Comment by rklaehn** [comment]
@b5 and @dignifiedquire it would be nice to have a decision whether this is happening soon or not.

I think we should do this as soon as possible, definitely before the end of the year. This to me is the missing item to be able to consider iroh-net complete in terms of API.

When using iroh-net as a library this is the one thing you will have to build stuff around. See what david had to do write his p2p thing: https://github.com/dvc94ch/p2p/blob/master/src/discovery.rs

**Comment by b5** [comment]
be the change @rklaehn. If you want this to happen design a workable solution we can debate. (for the record, I very much want to be able to dial without derp region as well)

**Comment by rklaehn** [comment]
> be the change @rklaehn. If you want this to happen design a workable solution we can debate. (for the record, I very much want to be able to dial without derp region as well)

I take this as a confirmation that I can spend some time on it. Currently discussing with @Nuhvi ...
