### ISSUE TITLE
Too much `send derp: message dropped, channel to actor is full` happens during intense import on low-profile servers.

### ISSUE THREAD

**Issue by ppodolsky** [n0-computer/iroh#2104]
At a certain point, Iroh, built from the master branch, starts to spam with 'send derp: message dropped, channel to actor is full' 2000-3000 times per second during import. This excessive output and corresponding attemts to fit into full channel reduces the overall performance of the import process, also making Iroh almost unresponsive.

Related discussion: https://discord.com/channels/949724860232392765/950683937661935667/1220100350607101997

**Comment by flub** [comment]
This has a sibling issue already: https://github.com/n0-computer/iroh/issues/1977 which covers the flow in the other direction IIUC.  DISCO messages received from the relay and going to the magicsock.

**Comment by flub** [comment]
There was a conversation on discord about this, these are my personal conclusions from it:

- We need to add backpressure to the channel so that `.poll_send()` refuses to send the packet instead of accepting it and then dropping it right away.  This will slow down the flow from quinn directly.  Of course when doing that we need to make sure the socket becomes writable again when the channel has space again.
- This also affects hole-punching: disco messages need to be relayed to establish holepunching.  If they get dropped because of an overflowing channel then we will not holepunch which in turn means we never take the pressure of this channel and it never recovers.
- This means we may need to consider adding two channels to the derp client: one for quic payloads and one for disco messages.  Disco messages are rather important, if the queue is filled up with quic messages then we risk losing disco messages.  However on the flipside someone could try and attack you by making you flood disco messages, taking up valuable relay capacity.
