### ISSUE TITLE
No way to generate a node ticket from the CLI

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#2248]
Now that we have dns, these are more useful.

**Comment by dignifiedquire** [comment]
> Now that we have dns, these are more useful.

how so? you really don't need node tickets, just use the node id, now that we have dns discovery

**Comment by cameronfyfe** [comment]
I originally asked because I was running `iroh-gateway` and it wanted `--default-node` to be a ticket, not a node id. I resolved my issue by adding node id to `iroh-gateway` (https://github.com/n0-computer/iroh-examples/pull/48) so don't need to export node tickets for that purpose anymore. Though maybe it'd still be useful in some cases?

**Comment by b5** [comment]
we're moving away from the CLI generally, closing as stale
