### ISSUE TITLE
flaky test: iroh-net magic_endpoint::tests::magic_endpoint_relay_connect_loop

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#2249]
Run: https://github.com/n0-computer/iroh/actions/runs/8874969273/job/24363415989

**Comment by divagant-martian** [comment]
This is due to graceful shutdown. Quinn seems to be notably slow sending close frames. From the run, the second client (client=1):

```log
2024-04-29T07:45:33.208363Z DEBUG client{i=1}: iroh_net::magic_endpoint: 604: Closing connections
2024-04-29T07:45:45.218914Z DEBUG client{i=1}: iroh_net::magic_endpoint: 610: Connections closed
```

I don't see a way to solve this on our end while behaving nicely to other peer when leaving. We should probably look into quinn's side to understand why was this so slow.

cc @flub

**Comment by flub** [comment]
That's 12 seconds to send the close frames??  That does not seem ok to me, there's no need for quinn to be that slow.  I wonder how slow it is on the successful tests.

**Comment by flub** [comment]
no longer marked flaky
