### ISSUE TITLE
Iroh fails when running through an outbound HTTPS proxy

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#2295]
* this user is running a proxy that forces outbound HTTP traffic onto a port that isn't 443
* router blocks outbound traffic on 443, it should follow redirects, apparently in the way recent versions of `reqwest` do
* log: https://gist.github.com/zicklag/d6e2fb694650cabcb556258f30dd7405
* from the user: "it looks like it fails with a couple timeouts, which is usually what happens when something tries to go outbound on 443 and the router blocks it."

**Comment by zicklag** [comment]
Further background, the most common way to configure the http(s) proxy is through environment variables: `http_proxy`, `https_proxy`, `no_proxy`, or their uppercase variants.

---

[This](https://github.com/n0-computer/iroh/blob/9d71fd84d39866dc53e76f53b3a32303cb9895ad/iroh-net/src/relay/http/client.rs#L562) appears to be the function in question. Since you're using hyper directly, instead of `reqwest` or `ureq` or some other http client library that already supports proxies, it might mean a bit more work for us. I think maybe the best route would be to try and lift the proxy logic from `reqwest` if possible. I'm pretty sure it also uses hyper.

**Comment by dignifiedquire** [comment]
https://github.com/siketyan/hyper-proxy2 looks like it should be easy to use
