### ISSUE TITLE
NodeAddr with a direct address incurs an extra RTT

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2546]
In #2509 we added an extra DISCO Ping-Pong exchange before we start using a direct address in all situations.  The reasoning was that this was a niche usecase which would not impact many real-life scenarios.

However it makes an iroh Endpoint no longer as good as a direct socket or QUIC endpoint.  If we have been given exactly one direct address we should start using it as well as using the relay path like before.  Otherwise we are significantly worse than a normal QUIC endpoint for this scenario and we do not want that.

If we do this, we may as well revert the entire decision and do the stable select again if there are multiple.  It seems a bit odd to now special-case this to just one direct address.

**Comment by divagant-martian** [comment]
I find the explanation reasonable enough and clear enough to be ok with a special case

**Comment by dignifiedquire** [comment]
you usually don't just get a single direct addr, most of the time it will be at least an IPv4 and IPv6 addr, at which point the special case would already fail to fix the issue though.

**Comment by Frando** [comment]
If I see things correctly, #2509 made connection establishment with direct addresses *much* slower. The cost is not an additional RTT in practice, but ~1s in waiting time until quinn re-sends the initial packets, which are lost because no validated address is available yet.

Before 2509:
```rust
// addr is a NodeAddr with only direct addresses
endpoint.add_node_addr(addr);
endpoint.connect_by_node_id(addr.node_id).await?;
// works and is fast!
```
On current main

// addr is a NodeAddr with only direct addresses
endpoint.add_node_addr(addr);
endpoint.connect_by_node_id(addr.node_id).await?;
```
```
 2024-07-31T22:08:25.774202Z ERROR poll_send{me=bbg6osx53doxyits}: iroh_net::magicsock: failed to send: no UDP or relay addr node=mwy7btpljbjy2lux
2024-07-31T22:08:25.775316Z  INFO poll_recv{me=bbg6osx53doxyits}:disco_in{node=mwy7btpljbjy2lux src=Udp(192.168.178.142:42563)}:handle_pong{m=Pong { tx_id: TransactionId(0x07
2E6E08F0C626C7B908F8E1), ping_observed_addr: Udp(192.168.178.142:11204) } src=Udp(192.168.178.142:42563)}: iroh_net::magicsock::node_map::best_addr: selecting new direct path
 for node addr=192.168.178.142:42563 latency=1.548481ms trust_for=6.499989536s
2024-07-31T22:08:26.773390Z  INFO poll_send{me=mwy7btpljbjy2lux}:get_send_addrs{node=bbg6osx53doxyits}: iroh_net::magicsock::node_map::node_state: new connection type typ=dir
ect
```
Note the ~1s delay between the two last log lines.
I think the reason is that this is the time that quinn waits until it retransmits the lost initial packets.

// works and is fast!
```
