### ISSUE TITLE
refactor: move ALL timeouts into one file

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#2602]
first step in centralizing our iroh-net timeouts to be able to give users a lever to adjust timeouts the way they want.

edit:
This is specifically about moving all of the existing timeouts into one location, so it's easier to work through #2337 and understand how all of the timeouts relate to each other.

**Comment by divagant-martian** [comment]
Having all configuration options in a single place would be nice. I would suggest we do it in a structured way, rather than flattening it. A small example (without actually looking into the needs of each module) would be

```rust
// in netcheck/config.rs
pub(crate) struct Config {
   whatever_timeout: Duration,
   ... // more stuff
}
```

this way netcheck can use it's configuration without going all the way up to the crate.

And then
```rust
// in iroh_net/config.rs
pub(crate) struct Config {
   netcheck_cfg: netcheck::Config
}
```

with this struct, or the endpoint, not sure, properly giving methods to set the values that are needed without potentially needing to access the inner structures. This is more refactor-friendly and self-contained than actually having all configuration options flattened.

**Comment by ramfox** [comment]
Ahh, okay this isn't about flattening configuration, it's about surfacing all the timeout defaults we have hardcoded as a first step to figuring out the best way to allow users to configure these. I should have been more specific, it's only about moving all of the `const` timeouts into one file, not changing any config options!
