### ISSUE TITLE
show progress bar for add

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#263]
Basic UX requirement that has a bunch of implications for the API. `iroh add` should show a progress bar by default, and however that progress bar is presented, the same API for subscribing to updates should be available to folks using iroh as a library.

We can expand progress bars to other commands in the future, this issue is for planning the underlying API for providing feedback, and representing that feedback with a progress bar on the command line

**Comment by faassen** [comment]
* initial phase where it scans directories, with scrollbar. (if adding a directory)
* then per file, an individual scrollbar. This wants to use some kind of multi scrollbar approach
* in the API we want to support getting progress information if we opt into it

We don't want to see the scrollbars if we're executing this in a script.

This looks like a good place to start:

https://docs.rs/indicatif/latest/indicatif/

I split off this issue from #270 as it's complicated enough to deserve its own.

**Comment by faassen** [comment]
As an experiment and because I was typing this into a file anyway, I'm going to report some of the progress of my analysis here in comments.

## Phases

Let's assume we're adding a directory; adding a file is a much simpler case that will do with a single progress bar.

When adding, we can distinguish two phases:

* setup phase, where we scan the directory and determine the files we want to upload
* multi progress phase, where for each file we show an individual progress bar (or spinner)

## iroh_share

`iroh_share` has an example of progress tracking. 

When a transfer is initiated, it creates a `Transfer` object. This object can be used to create a data object asynchronously (when things are really done), and obtain a progress stream synchronously. The progress stream can be used to get a stream of progress events, which can be done in a tokio task.

What's happening here is that the actual progress stream is forwarded using a sender/receiver, and the receiver is turned into a stream.

So in our API we could also return a `AddTransfer` object, which lets us get the outer CID (asynchronously, when all is done) and progress information. Possibly also more, like all added CIDs.

## Multi progress

We want multiple progress bars though. This follows the phases. We have a setup stream which has its own progress bar, to determine what files to upload. This stream produces individual streams for each file. We can then show progress bars for each stream.

## unit of progress

`add_dir` in `unixfs_builder` encodes a directory into a stream of cid, bytes tuples (parts). This works by encoding each file into parts. So it appears that a part can be seen as a unit of progress.

`size_hint` on Stream is a bound of lower and upper limit of how many elements in the stream remain. An exact `size_hint` would have lower and upper bound be the same.

Questions:

* do we know how many parts we will have in advance so we can implement size hint? It sounds possible as I think it's the file size divided by part size, but I need to confirm that.

* How do we implement `size_hint`?

**Comment by faassen** [comment]
## put

Once a part comes off the stream, it's put into the store using `store.put`. This talks to the store rpc client and also starts providing it through p2p.

So the unit of progress is part, and progress is made when the `put` is completed.

## determining the amount of parts for a file

`encode` in `File` creates an asynchronous reader stream for the file. Then the chunker creates a stream of chunks based on that reader. The chunker at present looks fully asynchronous. We need to have a way to provide the size hint here, which requires the total file size somehow; perhaps there's already a size hint we can exploit? Or perhaps we should add it.

## size_hint

The way to get the right information into all of these streams seems to involve implementing `size_hint` on various levels. Once we have accurate size hint information, we can determine the amount of parts per file and thus be able to show a per file scrollbar. For the outer "setup stream" we can't really use a size hint, as we really don't know how many files are in the directory. So for the outer setup phase, we need a spinner, not a scrollbar. We can use actual scrollbars for the files themselves.

**Comment by faassen** [comment]
## Single progress bar

I just had a sync discussion with @dignifiedquire about this. We came to the conclusion that since files get added one by one, having multiple progress bars, one for each file, makes little sense for now. We may introduce parallelism in the future and revisit it.

Instead we should use a single progress bar. The total is the amount of bytes we're uploading. We calculate this before we show the progress bar from the file tree. Associated with the progress bar is a status that shows which file we're uploading and how big it is, as well as the total size.

## streams

We need a stream of the files and their sizes to construct the progress bar, and may also be useful as part of the API itself. We consume this before we show the progress bar so we know how big it's supposed to be.

We also need a stream of filename, cid, bytes structures (probably a more nested structure). This is also useful as part of the API itself (to record cids produced, for instance). It'll be used to drive the progress bar too, as we derive the byte count from it as well as the current file to show in the status. (the size we can look up from what we got before)

**Comment by faassen** [comment]
## API

The API needs to produce:

* the final Cid result
* a stream of the files it is going to add, together with their sizes. This is required to calculate the total progress bar size.
* something like the stream we get from `dir.encode()`, but wrapped together with the file name

What does it do in the edge case where we only add a single file? I think we can return the same information - the scrollbar would work the same way. If we need to distinguish we can do so in the CLI as we know the path there.

Now going into the code:

### `add_dir` and `add_file`

These need to return a `dir.encode` stream decorated with path information, and the final CID result. I think the wrapping in path information can happen in `Directory::encode`.

### `Directory::encode`

This defers to `File::encode` which knows the path name to open it.

### repetition of path name

If a single path is split into multiple chunks, that means that we'd repeat a reference to the path for each element in the stream. That alternative is to segment the stream with an enum, so we get a "here's a new file" entry or a normal `Cid, Bytes` entry and update the status bar in the CLI each time we get a new file. But I think it's easier on the user of the API to always have the path for each chunk instead of having to remember it.

**Comment by faassen** [comment]
## What is a Content::Reader?

It can be built by `FileBuilder::build` based on the `FileBuild.reader` field, which can be initialized using `FileBuild::content_bytes` or `FileBuild::content_reader`. These are in use by tests, but is there another intended use? Would we be okay if we just made the `path` entry an `Option` for blocks we don't get from a file? Do we expect `Content::Reader` in an actual `add` interaction from the API?

**Comment by faassen** [comment]
## Next steps

* Create code that produces a stream of file paths and file sizes from a directory
* Code that can use this to calculate total amount of bytes
* Decorate the cid, bytes stream with path information (is bytes encoded? double check)

This should give us enough information from the API to support the progress bar (and ticker for the initial file sizes stream).

**Comment by b5** [comment]
closed by #368
