### ISSUE TITLE
iroh-net: netcheck actor dropped stun response channel

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#2647]
Have some reports of this happening quite often, inside docker (iroh@0.22)

```
ERROR iroh_net::netcheck::reportgen::hairpin: Hairpin actor failed: netcheck actor dropped stun response channel
at <..>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iroh-net-0.22.0/src/netcheck/reportgen/hairpin.rs:97
```

**Comment by flub** [comment]
I should summarise what I know from having looked at this:

- This happens when the netcheck actor is no longer running but the hairpin actor is not running anymore.
- This itself should not happen.
- **Maybe** it could happen at shutdown
  - All the actors involved (`netcheck -> reportgen -> hairpin`) are all supposed to abort on drop.
  - I think drop order might be fine but an not entirely sure.  If say the hairpin actor is dropped while it happens to be running what happens?  It first waits until it is pending again before it is dropped?
- If this happens during normal runtime that means the netcheck actor died.
  - This should also not happen!
  - Sounds a little similar to https://github.com/fishfolk/bones/issues/428 where possibly an actor dies which should not.
  - So I'm thinking of generically improving the actors supervision structure in MagicSock, but have currently no clue either here or at the https://github.com/fishfolk/bones/issues/42 issue whether that will really help.  It might expose the actual problem better though.

**Comment by flub** [comment]
Does it still happen to the original reporter?  (I assume you are a proxy)

**Comment by dignifiedquire** [comment]
I don’t know, will try to find out
