### ISSUE TITLE
share a CLI between iroh one and iroh cloud

### ISSUE THREAD

**Issue by faassen** [n0-computer/iroh#274]
Do we want to share the CTL implementation between iroh one and iroh cloud? The provisional answer is yes. This potentially affects the behavior of #268 #267 and #272, so if we go ahead with this we need to work out the details there.

In the API + CLI design I'm working on it's possible to swap out the API entirely for another, compatible implementation, as they're implemented as a trait. But the hope it that's not even necessary and use a RPC client for iroh one that exposes the relevant details. Work on this is being done in this PR https://github.com/n0-computer/iroh/pull/253 by @fabricedesre

**Comment by faassen** [comment]
If iroh-one was to be a single binary, how would you control the daemon once it's already running, for instance to do `add` and `get`? You'd still want to have a separate way to invoke these commands, and then communicating with the daemon externally, right?

**Comment by fabricedesre** [comment]
One way to do that can be roughly described as:
- if we don't find an existing running instance of iroh-one (see https://github.com/n0-computer/iroh/pull/231#issuecomment-1255288072), start in daemon mode.
- if we find a running instance, connect to it over grpc to execute commands.

I'm not sure what the command line arguments should be... Right now iroh-one has flags to set the store path, http port and a `--cfg` to point to a full configuration. Of course some of these don't make sense when you want to get/add content.

**Comment by b5** [comment]
> If iroh-one was to be a single binary, how would you control the daemon once it's already running, for instance to do add and get? You'd still want to have a separate way to invoke these commands, and then communicating with the daemon externally, right?

In kubo this is handled transparently, using a lockfile to find a running instance as @fabricedesre has described above. If a long running process is found, it's considered in possession of the lock, and command-invoking process delegates execution to the daemon process transparently via RPC.

My first question for you @faassen: how's that sound to you as someone who isn't mired in IPFS history? good thing? bad thing?

As an aside: there are at least a few common commands where kubo will error out when a daemon process is _not_ running, and it expects one. For example: running `kubo get` on a CID that isn't cached locally will error out. I'd like to see us _not_ error out in this scenario, and instead aim for all commands to just work, but I bring this up b/c it's very likely we'll need to cut this corner for an initial release

**Comment by fabricedesre** [comment]
> I'd like to see us _not_ error out in this scenario, and instead aim for all commands to just work, but I bring this up b/c it's very likely we'll need to cut this corner for an initial release

I think this will be easy to do once we have the lock file mechanism in place. It's basically a `if need_daemon && is_not_running { spawn_daemon() }` branch. This is what the `adb` utility used to manage android devices does for instance.

**Comment by faassen** [comment]
>     * if we don't find an existing running instance of iroh-one (see [Always delete an UDS file before binding it #231 (comment)](https://github.com/n0-computer/iroh/pull/231#issuecomment-1255288072)), start in daemon mode.

I think it's odd that the tool has two very different faces based on what's already running. Couldn't we just be explicit and have a `iroh serve` command to start serving it as a daemon? Then all the other commands can be used to connect to it. 

> In kubo this is handled transparently, using a lockfile to find a running instance as @fabricedesre has described above. If a long
> running process is found, it's considered in possession of the lock, and command-invoking process delegates execution to the
> daemon process transparently via RPC.

> My first question for you @faassen: how's that sound to you as someone who isn't mired in IPFS history? good thing? bad thing

As I described, just starting iroh in daemon mode if it's not already running sounds odd to me. What would it do if no iroh is running and I do `iroh get`? Or `iroh p2p id`? Should it keep running or exit? That's why I'd prefer an explicit command.

An explicit command like `iroh serve` is better but still somewhat weird to me, as `iroh` is both client and server. I don't expect to use `nginx` or `apache` to issue a HTTP GET request for me. To actually use `iroh` I'd need to invoke it twice, once to start the server and then to use it. I'm trying to think of precedents of the same binary being used to both provide the service as well as being the CLI to use it. They probably exist, just can't think of any right now and I'd feel more comfortable if I could. 

What is at least somewhat similar is games. You can run a game and have it host as a server for other games to connect to at the same time. That said, the person who hosts the game also plays it in the same session, and many games like Minecraft do ship separate server versions.

But it's not weird enough for me to get confused, and there's definitely a benefit to shipping a single binary that does everything (as long as it's not in a larger directory with support files, as then the benefit is mostly eliminated).
 
> I'd like to see us not error out in this scenario, and instead aim for all commands to just work

The notion that `iroh get` can work without `iroh` running somewhere confuses me a little. How would `iroh get` know where to look? Would it get the same configuration by itself and then connect to the store all by itself? Why stop there and not spin up more for a while to obtain the files from the wider network, then?

**Comment by fabricedesre** [comment]
@faassen my $0.02: as a end user, I could not care less if there's a daemon running or not. I just want `iroh get QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`to work. If that implies starting a daemon first, that's not something the end user should worry about. In that case having good defaults for the configuration helps since 

> I'm trying to think of precedents of the same binary being used to both provide the service as well as being the CLI to use it. They probably exist, just can't think of any right now and I'd feel more comfortable if I could.

`adb` is such a program. For instance if you run `adb devices` it first check if an adb server is running, and if not it spawns it (on my machine I now see this process `adb -L tcp:5037 fork-server server --reply-fd 4`) before completing the command.

**Comment by b5** [comment]
Ok, @dignifiedquire, @ramfox & I had a sync conversation to try to ingest the lessons here & come up with a concrete path forward in both the short and long term. Apologies, this one will be long-winded.

# Proposed Result
We think the best path for v0.1.0 is to have "iroh" the command line tool be a thin client that _always requires a long running process to delegate work to_. Iroh will be a uniform CLI that can delegate to either iroh-one or some set of {iroh-gateway, iroh-p2p, iroh-store}. iroh-one will be a single binary with a single command that starts the process, and exposes the same gatway,p2p, store RPC APIs, just running from a single process.

Iroh start will become a fancy alias for a shell invocation of `./iroh-one` that kicks off the iroh process.

The iroh CLI will error for _all_ commands when it cannot find an RPC API to communicate with. Iroh CLI will use configuration files (and default configuration values) to know which ports to look to for to connect to. This means configuration must explicitly set ports, getting a random port from the OS is disallowed.

In practice the best place to start with this is just to merge #253.

# Rationale

We're all in violent agreement with @fabricedesre's view that in the long run we don't want users to have to worry about deamons at all:

> as a end user, I could not care less if there's a daemon running or not. I just want "iroh get QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR" to work.

But pulling off "it just works" is going to take a long time. For example: it's possible to build `iroh get` that spawns a daemon when one doesn't exist, but in practice a cold-start iroh get will be _much_ slower than iroh get with a deamon running, because you'll need to hydrate a set of peers, traverse the DHT, etc. This adds up to a massive time disparity (on the lower end an additional 3-5 seconds, on the higher end to 1-2 minutes) based on weather or not a daemon is running. In practical terms this means it doesn't "just work" when a deamon isn't running, you have different behaviours based on what's going on in the background. Getting that "just works" level of parity will require re-designing large swathes of IPFS for the thin-client use case, which is work I very much think we should do, but while we do that work, we should default to telling users "you need to run a thing in all cases" gives us a sane default.

The online/offline behavioural difference for `iroh add` is worse, because we can't provide content without a libp2p host hooked up to a store. Again, we could ship an `iroh add` command that works offline, but online will provide, and offline will not. Which again means we need to explain the daemon to users.

This leads to the last thing we want to avoid, which is inconsistency. And while in theory the `if need_daemon && is_not_running { spawn_daemon() }` approach seems simple in theory, in practice it gets way stickier. For example: `kubo get $locally_cached_cid` will work offline, whereas `kubo get $remote_cid_not_stored_locally` will return `merkledag: not found`. Making things "just work" and keeping the offline hueristic would require a much more convoluted `if store_exists && has_cid(CID) { return cid } else { spawn_daemon(); fetch_cid(CID) }`. But the real problem here is the UX:  we have different behaviours _based on the content we asked for_, which may be technically accurate in a permacache system, it's super confusing.

So, in the near-term **we can't have an IPFS implementation that behaves consistently in both online and offline states.** We can either:
1. Have consistent behaviour, and require users learn about a "server"
2. Have inconsistent behaviour.

We'd like to choose the former, which aligns us with @faassen's "outsider's intuition": 

> I think it's odd that the tool has two very different faces based on what's already running. Couldn't we just be explicit and have a iroh serve command to start serving it as a daemon? Then all the other commands can be used to connect to it.

So, _everything_ require an iroh start command, and we'll write documentation that shows users they need iroh before they can do stuff. the Iroh command line client becomes a thin client that issues RPC requests to some set of processes, getting #253 merged is a great start. This creates a lot of work for @faassen, and stomps all over what @rklaehn wanted to see for an initial iteration, but it's consistent.

Long term, we can do better, but I want to work through _all_ the details before we claim some improvement on this status quo.

**Comment by fabricedesre** [comment]
About lowering latency, I implemented racing p2p with raw blocks from a gateway in capyloon's fork (see https://github.com/capyloon/iroh/blob/capyloon/iroh-one/src/content_loader.rs) and that helps - the gateway perf in general is all over the place so sometimes the p2p stack wins! Happy to upstream if you're interested.

**Comment by faassen** [comment]
Does this make a difference in us moving the `iroh` CLI into `iroh-one` versus it staying in `iroh-ctl`?

**Comment by Arqu** [comment]
> About lowering latency, I implemented racing p2p with raw blocks from a gateway in capyloon's fork (see https://github.com/capyloon/iroh/blob/capyloon/iroh-one/src/content_loader.rs) and that helps - the gateway perf in general is all over the place so sometimes the p2p stack wins! Happy to upstream if you're interested.

FYI this only helps because our current `iroh-p2p` crate resolves really bad and we've been working on it for the past month aggressively. Once done, this shouldn't be needed on your end.

------------------

My summary response for the above regarding ctl <> iroh comms is that I agree with most if not all of it. My "request" for this piece of work is that we don't do what kubo does currently where we have "offline" and "online mode". It should be either it works the same offline and online so it's irrelevant (e.g. `store add abc.xyz` where you can spawn store if not running, write and close) or simply require things are online.

**Comment by fabricedesre** [comment]
> FYI this only helps because our current `iroh-p2p` crate resolves really bad and we've been working on it for the past month aggressively. Once done, this shouldn't be needed on your end.

There are contexts where running the p2p dht is a no go, for power and network usage reasons. If you don't tackle that you can't claim to be mobile ready. "Trustless Edge Gateways" would help a lot with that.

**Comment by faassen** [comment]
One argument in favor of placing the CLI in `iroh-one` is so that `iroh start` can just start `iroh-one` as a subprocess, as per #290

**Comment by b5** [comment]
marking this one as closed. We've decided that `iroh` will be a single CLI that can speak to iroh one and iroh cloud. release v0.1.0 will only support the "cloud" configuration, with a bunch of things that will work by coincidence with iroh-one. We'll turn our attention to getting the iroh-one daemon API right in a future release.
