### ISSUE TITLE
iroh does not work with relays without STUN on networks without UPnP

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2876]
To reproduce, create `iroh.toml` file in the root of this repo checkout:
```
$ cat iroh.toml
[[relay_nodes]]
url = "https://iroh.testrun.org.:4443"
stun_only = false
stun_port = 3478
```

https://iroh.testrun.org.:4443 is running iroh-relay 0.25.0.

Then run:
```
$ cargo run -p iroh-cli -- --config ./iroh.toml doctor accept
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/iroh --config ./iroh.toml doctor accept`
Error: wait for relay connection

Caused by:
    deadline has elapsed
```

On a network with UPNP it works:
```
$ cargo run -p iroh-cli -- --config ./iroh.toml doctor accept
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/iroh --config ./iroh.toml doctor accept`
Connect to this node using one of the following commands:

	Using the relay url and direct connections:
iroh doctor connect ...
...
```

The problem is present since iroh 0.27.0. More precisely, commit https://github.com/n0-computer/iroh/commit/5e40fe138f9581a195d47c251992e3de8b1ec8c1, PR https://github.com/n0-computer/iroh/pull/2804

This PR pulled in commit https://github.com/dariusc93/rust-igd/commit/56934bb216149d1988c333c61e7c1d88a1868eb8 of rust-igd (`igd-next` crate) that was merged from PR https://github.com/dariusc93/rust-igd/pull/8

**Comment by Arqu** [comment]
Well that mostly depends on your firewall setup as most VPSs will get a public IP and won't need additional port forwarding shenanigans. 
Alternatively as you suggested elsewhere, running over a mobile hotspot will for most users produce a NAT without UPNP type topology.

**Comment by dignifiedquire** [comment]
So, we figured out roughly the list of things that went wrong

- for netcheck `OVERALL_REPORT_TIMEOUT` is set to 5seconds, which means, that if this timer expires, the report is considered faulty and is thrown away
- usually enough probes return before this, so this is never hit
- igd-next@0.15 has a bug, which doesn't respect the timeout on `search_gateway` anymore, but rather hardcoding a 5 second timeout
- in the case of using `iroh.testrun.org` with disabled STUN, all STUN probes would hang/timeout when this is combined with no upnp gateway, we end up timing out the whole report (because upnp waits for 5seconds, instead of configured 3), resulting in netcheck considering the whole report failed, which ends up generating the above error

A prototype fix is in https://github.com/n0-computer/iroh/pull/2877/commits/2eb3c8f31d3a66d8d924860747ae6c81e62bc854 which will need cleanup, but in all my testing shows to fix the issue
